### PR TITLE
improve research page

### PR DESCRIPTION
**Pull request by rista404**
- [x] add filtering by tag, author and conference
- [x] add clear all filters

image

- [x] add links to the team page, for team members

image

- [x] add a link to the research page to the homepage

image

___

@k4m4 how does everything look? do you think it would be useful to click on the filters and see all values in a select-popup? (might be too much for conferences)

### CODE REVIEW

**Comment by k4m4** [comment]
Looking great @rista404, thanks a ton! We're going over it with Haris and have a few suggestions:
- Would be great if we can filter with multiple tags, instead of just one. Same for authors.
- The "View profile" button seems a bit out of place. Maybe we can replace it with some icon indicating that it's a CP member?
- Would be nice if the paper titles also get underlined on hover
- We need to standardize the conference names, i.e., if I filter for Financial Cryptography, it should show all FC papers, irrespective of the year.
- As for linking to the research page from the home page, let's have a nav bar with a few links on the top right, for now? "Team | Research | Projects"

**Comment by k4m4** [comment]
> Added "❖" as a symbol for the author profile link, what do you think? I also tried "↗", "⎋", "*" but I found the first one interesting. I also went ahead and separated the conference name and year in the data source, so filtering works better.

"❖" looks good. Maybe we could also try a minimal CP logo icon, once we have that. There's a designer working on it.

> > Would be great if we can filter with multiple tags, instead of just one. Same for authors.
> Quick question regarding this, should this work as "tag-a" AND "tag-b" (showing conferences that have both), or "tag-a" OR "tag-b"? Same for authors. I guess it should be AND to narrow down the filtering even further?

AND is what we had in mind.

**Comment by rista404** [comment]
@k4m4 you can now click author names and tags to add/remove from filters. I guess there could be improvements from the UX perspective so users know they can do this (right now there's only a `title` on these buttons saying "Filter by this x.") but I think it's shippable :shipit:

**Review by k4m4 — APPROVED** [review]
Looks great, thank you @rista404! Let's ship it.

**Pull request merged**
